pipeline {
    agent any
    options {
    // 'Preparing for the build'
    // This is required if you want to clean before build
        skipDefaultCheckout(true)
    }

    environment {
     // Environment variables for the pipeline
        JENKINS_HOME = "$JENKINS_HOME"
        BUILD = "${JENKINS_HOME}/workspace/mlops"
    }

    stages {
        stage('Stop and remove container') {
            steps {
                script {
                    sh 'docker stop translator-app && docker rm translator-app || true'
                }
            }
        }
        stage('Remove image') {
            steps {
                script {
                    sh 'docker rmi translator-img || true'
                }
            }
        }
        stage('Preparation') {
        // 'Preparing for the build'
            steps {
                checkout scm
                cleanWs()

            }
        }

        stage('Checkout') {
        // 'Checking out the repository'
            steps {
                checkout scm
                git 'https://github.com/nocsland/urfu_mlops.git'
            }
        }

        stage('Build image') {
        // 'Building the Docker image'
            steps {
                script {
                    dir('translator/') {
                        sh 'docker build -t translator-img .'
                    }
                }
            }
        }

        stage('Run container') {
        // 'Running the Docker container'
            steps {
                script {
                    sh 'docker run -d -p 8000:8000 --name translator-app translator-img'
                }
            }
        }
    }
}